version: "3.8"
services:
  nginx:
    image: nginx
    container_name: nginx
    ports: 
      - 80:80
      - 443:443
    volumes: 
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config:/etc/other
    links:
      - server
      - web
  server:
    build: ./zerb_FE
    container_name: server
    restart: always
    ports:
      - 5000:5000
      - 3002:3002
  web:
    build: ./zerb_BE
    container_name: web
    restart: always
    ports:
      - 8080:8080
    external_links:
      - "server:server"